### ISSUE TITLE
Compilation instructions

### ISSUE THREAD

**Issue by FrancoisDupayrat** [CloakProject/CloakCoin#2]
Hello,

There isn't any compilation instruction on the README, could you provide step-by-step instructions on how to compile the project?

Thanks.

**Comment by porky11** [comment]
There are. Here you see, where to find it: https://github.com/CloakProject/Cloak2Public/blob/anorak_master/INSTALL

**Comment by FrancoisDupayrat** [comment]
Thanks, but why don't you put that directly on the README? 

That's the first and often only thing a fresh potential contributor will look at.
