### ISSUE TITLE
erratic messages spamming debug.log 

### ISSUE THREAD

**Issue by chlorocryptos** [CloakProject/CloakCoin#27]
the 'debug.log' file is spammed with erratic messages, reading:

&gt; &gt; &gt; Unrecognized message received: ann0010
or 
&gt; &gt; &gt; Unrecognized message received: ann0011

these messages appear in the hundreds.
what do they mean ?
do they possibly originate from connected nodes with older versions of the cloakcoin wallet ?  

cloakcoin qt wallet v. 2.2.2.2
windows 7 64 bit

**Comment by linuxuser234** [comment]
Hi there,
i can confirm the many debug.log - entries: 

">>> Unrecognized message received: ann9>>>..."
">>> Unrecognized message received: ann0010>>>...."

cloakcoin qt 2.2.2.2
Ubuntu disco 19.04

**Comment by anorakthagreat** [comment]
Yes, these are just Enigma announcements from older CloakCoin nodes. Nothing to worry about.

**Comment by chlorocryptos** [comment]
ok, fine, good to know...
thx
