### ISSUE TITLE
Problems with compiling: Bignum

### ISSUE THREAD

**Issue by porky11** [CloakProject/CloakCoin#3]
When trying to compile I get many errors because of some bignum type.
The first error I get looks like this:
```
In file included from src/main.h:8:0,
                 from src/kernel.h:7,
                 from src/txdb-leveldb.cpp:17:
src/bignum.h:51:24: error: invalid use of incomplete type 'BIGNUM {aka struct bignum_st}'
 class CBigNum : public BIGNUM
```
I'm using Arch Linux, so maybe it's a problem with dependencies and versions.

**Comment by HydraGene** [comment]
I also get multiple "bignum¨ errors. It starts with the same error as @porky11 
I'm using Debian Stretch.  

I searched and found that it may be an openssl version problem. At least one error, that I got, said something about BN_init. My search found: "BN_init() was removed in OpenSSL 1.1.0; use BN_new() instead." Hope this helps..

**Comment by anorakthagreat** [comment]
You are trying to compile the code with OpenSSL 1.1.x which is not backwards compatible with 1.0.x
Please compile against openssl1.0.x .
